### ISSUE TITLE
Checklist para revisar el paquete

### ISSUE THREAD

**Issue by yabellini** [JuanMLeoni/NimbusR#1]
A lo largo de las secciones los ejercicios transversales que llamamos "Construyendo un paquete de R paso a paso" son una guía para, justamente, construir un paquete que lee y ayuda a analizar datos meteorológicos. 

A continuación encontrarás una lista de elementos que debe tener o con los que debe cumplir el paquete para estar completo. 

- [x] Estructura del paquete
- [x] Repositorio local
- [x] Repositorio remoto

## DESCRIPTION

- [x] Título
- [x] Descripción
- [x] Las personas involucradas estan listadas en Auth@rs

## Funciones y datos

- [x] (al menos) 3 funciones
- [x] (al menos) 1 set de datos

## Documentación

- [x] Todas las funciones y datos están documentados
- [x] README completo
- [x] Incluye una viñeta que explica como usar las funciones
- [x] El paquete tiene una página web

## Tests

- [x] El paquete tiene tests que cubren al menos el 75% del código de las funciones
- [x] El paquete tiene una GitHub action que revisa la covertura de los tests
- [x] El paquete pasa R CMD checks
- [x] El paquete tiene una GitHub action que chequea el paquete en distintos sistemas operativos

## Otros

- [x] Incluye una licencia
- [x] El README incluye instrucciones sobre:
  - [x] como instalar el paquete.
  - [x] los autores. 
  - [x] como se puede contribuir al paquete.

**Comment by Maximo-Verdondoni** [comment]
@yabellini @paocorrales
El paquete ya está terminado, lo único que queremos arreglar es que no carga el logo en la página del paquete

**Comment by paocorrales** [comment]
El logo debe estar en la carpeta man/figures. Pueden revisar la documentación https://pkgdown.r-lib.org/reference/build_home.html o la función `usethis::use_logo()`

**Comment by Maximo-Verdondoni** [comment]
Buenas @yabellini @paocorrales !

Estoy lidiando para limpiar la nota:
checking for non-standard things in the check directory ... NOTE
  Found the following files/directories:
    'NH0046.csv' 'NH0098.csv' 'NH0437.csv' 'NH0472.csv' 'NH0910.csv'
    
Estuve googleando y mucha info no encontré, parece que los datos quedan guardados en el directorio del check:
![image](https://github.com/user-attachments/assets/b364b098-a6fa-4ee9-ae7e-84a2bdd55413)

Pero no logro conseguir que estos se borren, probé con unlink() en los test por si era eso pero tampoco parece funcionar

**Comment by paocorrales** [comment]
Chicos el problema se general porque en los ejemplos de las funciones `get..` descargan los datos en la carpeta raiz, por ejemplo:

```
#' getNH0046("NH0046.csv")
```

Esto hace que cuando corre R CMD, corren los ejemplos y se descagar estos archivos que quedan en la carpeta de los checks. Por eso la nota. 

Les recomiendo que en los ejemplos manden los archivos a una carpeta temporal con `tempdir()`

**Comment by Maximo-Verdondoni** [comment]
Ahhh claro pruebo entonces, gracias!
